import type { Metadata } from 'next';

// import { CacheProvider } from '@emotion/react';
// const clientSideEmotionCache = createEmotionCache();
// import { createEmotionCache } from '../utils/emotion-cache';

import { Header } from './_components/header';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en' dir='ltr' suppressHydrationWarning>
            <body className={``}>
                {/* <CacheProvider value={clientSideEmotionCache}> */}
                <Header />
                <main>{children}</main>
                {/* </CacheProvider> */}
            </body>
        </html>
    );
}
